// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAonICD0PLnT8uHWaMwlLUhprdTSXvjH58',
    appId: '1:147767525014:web:72ebbce9484b6f19a78cb7',
    messagingSenderId: '147767525014',
    projectId: 'feline-skin-disease-detection',
    authDomain: 'feline-skin-disease-detection.firebaseapp.com',
    storageBucket: 'feline-skin-disease-detection.firebasestorage.app',
    measurementId: 'G-WSEF3WG8ZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSqRtTnLX8XhHVK365uUDNyLD8Xn7AMCQ',
    appId: '1:147767525014:android:0bfb8e6098d6ddc9a78cb7',
    messagingSenderId: '147767525014',
    projectId: 'feline-skin-disease-detection',
    storageBucket: 'feline-skin-disease-detection.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQzoNfEmlKugiU5pN2Xp9j9q4A8QPoM8k',
    appId: '1:147767525014:ios:6f895cc84ca83eada78cb7',
    messagingSenderId: '147767525014',
    projectId: 'feline-skin-disease-detection',
    storageBucket: 'feline-skin-disease-detection.firebasestorage.app',
    iosBundleId: 'com.example.finalDesign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQzoNfEmlKugiU5pN2Xp9j9q4A8QPoM8k',
    appId: '1:147767525014:ios:6f895cc84ca83eada78cb7',
    messagingSenderId: '147767525014',
    projectId: 'feline-skin-disease-detection',
    storageBucket: 'feline-skin-disease-detection.firebasestorage.app',
    iosBundleId: 'com.example.finalDesign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAonICD0PLnT8uHWaMwlLUhprdTSXvjH58',
    appId: '1:147767525014:web:be0cde967123e655a78cb7',
    messagingSenderId: '147767525014',
    projectId: 'feline-skin-disease-detection',
    authDomain: 'feline-skin-disease-detection.firebaseapp.com',
    storageBucket: 'feline-skin-disease-detection.firebasestorage.app',
    measurementId: 'G-3ZS8LDMYFC',
  );
}
